version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=SmartCityDb;User=sa;Password=Your_password123;"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

Entity Framework Core_ bash:

dotnet add package Microsoft.EntityFrameworkCore.SqlServer
dotnet add package Microsoft.EntityFrameworkCore.Design
